version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    container_name: app1
    image: puemmth/client_loadbalancer:latest
    ports:
      - "9001:80"

  app2:
    container_name: app2
    image: puemmth/client_loadbalancer:latest
    ports:
      - "9002:80"

  app3:
    container_name: app3
    image: puemmth/client_loadbalancer:latest
    ports:
      - "9003:80"
