version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3
  server1:
    image: puemmth/client_loadbalancer:latest
    container_name: server1
    ports:
      - "8081:80"
    environment:
      - SERVER_NAME=server1

  server2:
    image: puemmth/client_loadbalancer:latest
    container_name: server2
    ports:
      - "8082:80"
    environment:
      - SERVER_NAME=server2

  server3:
    image: puemmth/client_loadbalancer:latest
    container_name: server3
    ports:
      - "8083:80"
    environment:
      - SERVER_NAME=server3
